name: Build FileZap Components

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-client:
    name: Build GUI Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Build GUI Client
        run: ./build.sh client

      - name: Upload GUI Client Artifact
        uses: actions/upload-artifact@v3
        with:
          name: filezap-client
          path: bin/client/*

  build-validator:
    name: Build Validator Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Build Validator Server
        run: ./build.sh validator

      - name: Upload Validator Server Artifact
        uses: actions/upload-artifact@v3
        with:
          name: filezap-validator
          path: bin/validator/*
